apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

namePrefix: staging-

replicas:
  - name: microapp
    count: 2

configMapGenerator:
  - name: microapp-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO

images:
  - name: REGISTRY_URL/microapp
    newTag: STAGING_TAG
